version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - vote
      - result
    networks:
      - frontend

  vote:
    build: ./vote
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - frontend
      - backend

  result:
    build: ./result
    environment:
      - DB_HOST=db
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - frontend
      - backend

  seed:
    build: ./seed-data
    depends_on:
      - db
    networks:
      - frontend

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - redis
      - db
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votes
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
    driver: bridge
