version: '3.8'

services:
  nginx:
    image: europe-west9-docker.pkg.dev/login-k8s-416409/voting-images/voting-image/nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - vote1
      - vote2
      - result
    networks:
      - front-net

  vote1:
    image: europe-west9-docker.pkg.dev/login-k8s-416409/voting-images/voting-image/vote1
    build: ./vote
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000" #exposed for testing locally
    depends_on:
      - redis
    networks:
      - front-net
      - back-net

  vote2:
    image: europe-west9-docker.pkg.dev/login-k8s-416409/voting-images/voting-image/vote2
    build: ./vote
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - front-net
      - back-net

  result:
    image: europe-west9-docker.pkg.dev/login-k8s-416409/voting-images/voting-image/result
    build: ./result
    environment:
      - DB_HOST=db
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - front-net
      - back-net

  seed:
    image: europe-west9-docker.pkg.dev/login-k8s-416409/voting-images/voting-image/seed
    build: ./seed-data
    depends_on:
      - db
      - nginx
    networks:
      - front-net

  worker:
    image: europe-west9-docker.pkg.dev/login-k8s-416409/voting-images/voting-image/worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - redis
      - db
    networks:
      - back-net

  redis:
    image: redis:latest
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: ["CMD", "sh", "/healthchecks/redis.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - back-net

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votes
    volumes:
      - ./healthchecks:/healthchecks
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "sh", "/healthchecks/postgres.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - back-net

volumes:
  db-data:

networks:
  front-net:
  back-net:
    driver: bridge
