apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/login-k8s-416409/voting-images/voting-image/result
        name: result
        ports:
        - containerPort: 4000
          name: result
        livenessProbe:
          httpGet:
            path: /
            port: 4001
