apiVersion: batch/v1
kind: Job
metadata:
  name: seed-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: seed
        image: europe-west9-docker.pkg.dev/login-projet-420022/voting-image/seed
      restartPolicy: Never
  backoffLimit: 4

