apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  template:
    spec:
      containers:
      - name: seed
        image: europe-west9-docker.pkg.dev/login-k8s-416409/voting-images/voting-image/seed
        command: 
          - python make-data.py
          - chmod +x ./generate-votes.sh
          - ./generate-votes.sh
      restartPolicy: Never