apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/login-k8s-416409/voting-images/voting-image/vote
        name: vote
        ports:
        - containerPort: 5000
          name: vote
        livenessProbe:
          httpGet:
            path: /
            port: 5001
